
services:
  suricata:
    image: jasonish/suricata
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: suricata -c /etc/suricata/suricata.yaml -i eth0
    volumes:
      - ./suricata:/etc/suricata
    restart: unless-stopped

  zeek:
    image: zeek/zeek:latest
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: zeek -i eth0  
    volumes:
      - ./zeek:/pcap
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped

  thehive:
    image: thehiveproject/thehive4:4.0.2
    ports:
      - "9000:9000"
    environment:
      - STORAGE_PASSWORD=secret
    restart: unless-stopped

  cortex:
    image: thehiveproject/cortex:latest
    ports:
      - "9001:9001"
    restart: unless-stopped

  owasp-zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
    ports:
      - "8090:8090"
    volumes:
      - ./zap/config:/zap/config  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/JSON/core/view/version/"]
      interval: 30s
      timeout: 10s
      retries: 3  
    restart: unless-stopped

  clamav:
    image: mkodockx/docker-clamav
    ports:
      - "3310:3310"
    restart: unless-stopped

volumes:
  misp-postgres-data:
  pgadmin-data:
